version: '3.8'

services:
  log-forwarder:
    build: .
    container_name: log-forwarder
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
    environment:
      - TZ=UTC
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import socket; socket.socket().connect(('localhost', 514))"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - log-network

networks:
  log-network:
    driver: bridge 